############################################################
# top level directories
sourcedir: /work/project/ext_016/RNA-Seq-Variant-Calling_1/source_dir_6
refdir: /work/project/ext_016/RNA-Seq-Variant-Calling_1/Reference_genomes
############################################################
# reference files, genome indices and data
reference:
  stargenomedir:
    hg38: $refdir/starindex2/hg38index2/hg38

  fasta:
    hg38: $refdir/hg38/GRCh38.p13.genome.fa 

  gtf:
    hg38: $refdir/hg38/gencode.v38.annotation.gtf
  
  1000G:
    hg38: $refdir/hg38/1000G_phase1.snps.high_confidence.hg38.vcf
  
  Indels:
    hg38: $refdir/hg38/Mills_and_1000G_gold_standard.indels.hg38.vcf.gz
  
  DbSNP:
    hg38: $refdir/hg38/Homo_sapiens_assembly38.dbsnp138.vcf


  star_ref: "/work/project/ext_016/RNA-Seq-Variant-Calling_1/Reference_genomes/starindex/hg38index"


# directory structure for input and output files

datadirs:
  fastq: $sourcedir/demo_data
  qc: $sourcedir/qc_output
  trim: $sourcedir/trimmed_files
  bam: $sourcedir/pass1
  sj_files: $sourcedir/sj_files
  pass2: $sourcedir/pass2
  RGbam: $sourcedir/RGbam
  dedup: $sourcedir/dedup
  splitNcigar: $sourcedir/splitNcigar
  Recal1: $sourcedir/Recal1
  BQSR_1: $sourcedir/BQSR_1
  Recal2: $sourcedir/Recal2
  BQSR_2: $sourcedir/BQSR_2
  vcf: $sourcedir/vcf
  annotated: $sourcedir/annotated
  vcf_new: $sourcedir/vcf_new
  filtered: $sourcedir/filtered
  CombinedGvcfs: $sourcedir/CombinedGvcfs
